- src/main/java/umc/forgrad/ForGradApplication.java
> 현주 커밋,푸쉬 확인

- src/main/java/umc/forgrad/exception/ExceptionAdvice.java
- src/main/java/umc/forgrad/exception/GeneralException.java
ApiRespnose를 에러로 리턴할 수 있도록 수정
- status code를 클라이언트로 반환 가능(200, 400, 401, ...)
> 에러 처리 코드 수정

- src/main/java/umc/forgrad/controller/GradInfoController.java
- src/main/java/umc/forgrad/converter/GradInfoConverter.java
- src/main/java/umc/forgrad/dto/gradinfo/GradInfoResponseDto.java
- src/main/java/umc/forgrad/service/info/CompletionQueryService.java
- src/main/java/umc/forgrad/service/info/CompletionQueryServiceImpl.java
> 이수현황 탭 조회 기능 구현

- src/main/java/umc/forgrad/dto/student/StudentResponseDto.java
> conflict resolve 코드 추가

- src/main/java/umc/forgrad/service/common/ConnectionResponse.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- src/main/java/umc/forgrad/service/info/CompletionQueryServiceImpl.java
- src/main/java/umc/forgrad/service/info/GradInfoQueryServiceImpl.java
- src/main/java/umc/forgrad/service/info/GradesQueryServiceImpl.java
- src/main/java/umc/forgrad/service/point/PointQueryServiceImpl.java
중복되는 메소드 common 패키지에 static 메소드로 추출
> http 요청 메소드 중복 제거

- src/main/java/umc/forgrad/service/student/StudentCommandServiceImpl.java
- 한성대 서버 점검으로 인해 리턴되는 쿠키 값의 key 값이 변경됨에 따라 키 값 변경
> 쿠키 key 값 변경됨

- src/main/java/umc/forgrad/config/WebConfig.java
- src/main/java/umc/forgrad/filter/CustomServletWrappingFilter.java
- src/main/java/umc/forgrad/interceptor/LoggingInterceptor.java
> Intercepor를 이용한 Logging 기능 구현

- src/main/java/umc/forgrad/config/WebConfig.java
> id, passwd 로그 제외

- src/main/java/umc/forgrad/dto/student/StudentResponseDto.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- 홈화면 조회시 Base64Image 타입의 문자열 추가
> 홈화면 조회시 이미지 추가

- src/main/java/umc/forgrad/converter/FuturePlansCoverter.java
- src/main/java/umc/forgrad/dto/student/StudentResponseDto.java
- src/main/java/umc/forgrad/repository/SemesterRepository.java
- src/main/java/umc/forgrad/repository/SemesterSubjectRepository.java
- src/main/java/umc/forgrad/repository/SubjectRepository.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- 다음 학년, 학기 기준으로 향후계획의 시간표 리턴
- 시간표 총학점 필드 추가
- 홈화면 ResponseDto 구조 변경
- 시간표 조회시 SemesterRepository에서 중복키 문제 해결
> 홈화면 조회 기능 변경

- src/main/java/umc/forgrad/repository/SubjectRepository.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- sumCredits가 null일 때 0 리턴하도록 변경
> sumCredits가 null 일 때 0

- README.md
- src/main/java/umc/forgrad/repository/SubjectRepository.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- sumCredits가 null일 때 0을 리턴하도록 변경
> 수정된 코드 서버 적용

- .github/workflows/build.yml
- .github/workflows/deploy.yml
> build, deploy 파일 이름 바뀐거 수정

- .github/workflows/deploy.yml
- merge 되었을 때 코드 제거
- pr 올리면 deploy가 skip됨
> deploy 동작 변경

- src/main/java/umc/forgrad/config/WebConfig.java
- Interceptor에 의해 스웨거 페이지 막히는 문제 해결
- main pr시 deploy 되어버리는 문제
> exclude swagger path

- src/main/java/umc/forgrad/apipayload/code/status/ErrorStatus.java
- src/main/java/umc/forgrad/repository/SemesterRepository.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- 존재하지 않는 학기에 대한 처리 변경(optional 제거, 학기가 존재하지 않을 수 있기 때문에 빈 list 반환)
> 존재하지 않는 학기 반환 처리 변경

- .gitmodules
- src/main/java/umc/forgrad/domain/Free.java
- src/main/java/umc/forgrad/domain/Student.java
- Student 테이블에서 Free OneToOne 관계 제거
- Free 테이블에 학생 정보 두기
> Student, Free 연관관계 변경

- src/main/java/umc/forgrad/controller/GradDateController.java
- src/main/java/umc/forgrad/converter/GradDateAndMessageConverter.java
- src/main/java/umc/forgrad/converter/StudentConverter.java
- src/main/java/umc/forgrad/domain/Student.java
- src/main/java/umc/forgrad/dto/student/StudentRequestDto.java
- src/main/java/umc/forgrad/dto/student/StudentResponseDto.java
- src/main/java/umc/forgrad/service/student/GradDateService.java
- src/main/java/umc/forgrad/service/student/GradDateServiceImpl.java
- 현재날짜, 졸업예정날짜, d-day 계산해서 리턴하도록 변경
- 졸업예정일, 응원의 한마디 업데이트 로직 수정
> 졸업예정 페이지 기능 추가

- src/main/java/umc/forgrad/converter/GradDateAndMessageConverter.java
- src/main/java/umc/forgrad/dto/student/StudentResponseDto.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
> 홈화면 조회시 d-day 필드 추가

- src/main/java/umc/forgrad/converter/GradInfoConverter.java
- src/main/java/umc/forgrad/dto/gradinfo/GradInfoResponseDto.java
- src/main/java/umc/forgrad/service/info/CompletionQueryServiceImpl.java
- 다른 계정으로 조회 시 html 구조 문제 때문에 조회 안되는 문제 해결
> 이수현황 조회 로직 변경

- src/main/java/umc/forgrad/dto/gradinfo/GradInfoResponseDto.java
- src/main/java/umc/forgrad/service/info/GradesQueryServiceImpl.java
- html 구조 차이로 인해 조회가 안되는 문제 해결
- 학점 조회 페이지 변경
- 조회 로직 변경(최대한 태그 기준으로 값을 찾게 함)
> 성적 정보 조회 로직 변경

- src/main/java/umc/forgrad/converter/GradDateAndMessageConverter.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- src/main/java/umc/forgrad/service/student/StudentCommandServiceImpl.java
- 로그인시 Student 객체를 새로 만드는 문제 해결
- d-day 날짜 계산 인자 변경(Student -> LocalDate)
> 로그인시 학생 정보 초기화 되는 문제 해결

- src/main/java/umc/forgrad/converter/GradDateAndMessageConverter.java
- src/main/java/umc/forgrad/service/activityService/ActivityCommandService.java
- src/main/java/umc/forgrad/service/home/HomeQueryServiceImpl.java
- src/main/java/umc/forgrad/service/student/StudentCommandServiceImpl.java
- 로그인시 Student 객체를 새로 만드는 문제 해결
- d-day 날짜 계산 인자 변경(Student -> LocalDate)
> 로그인시 학생 정보 초기화 문제 해결
